1. Added a functioning landing page 2. Changed Green circle to cash app logo 3. Added animation effects for navigation bar 4. Also added animation effects for " text " and "image " to fade in - but not functioning yet
SaahilKapasi/CSC207-Project pull request #28
Opened 2024-11-25 22:33 UTC by aainagargg

Particular details mentioned in the commit message.

2024-11-26 19:17 UTC, SaahilKapasi commented
It'd be great if you modify this so that it works with the latest backend code, currently this frontend code is still looking for fprVarianceScore and fprMeanScore when only fprScore exists now.

2024-11-26 21:30 UTC, YesIfwRONG commented
> It'd be great if you modify this so that it works with the latest backend code, currently this frontend code is still looking for fprVarianceScore and fprMeanScore when only fprScore exists now.

In my branch, I changed the frontend to look for fprScore instead. As long as we merge both mine and hers, things should work, if nothing unexpected happens.

2024-11-26 21:30 UTC, YesIfwRONG approved these changes

2024-11-26 22:05 UTC, SaahilKapasi commented
> > It'd be great if you modify this so that it works with the latest backend code, currently this frontend code is still looking for fprVarianceScore and fprMeanScore when only fprScore exists now.
> 
> In my branch, I changed the frontend to look for fprScore instead. As long as we merge both mine and hers, things should work, if nothing unexpected happens.

If possible I'd like to see a deployed version before merging anything. The merge conflicts also have to be resolved, could you try merging your branch into hers or vice versa?

2024-11-26 22:12 UTC, aainagargg commented
@YesIfwRONG are you working on merging, refactoring this then?

2024-11-27 20:09 UTC, CodeYimin requested changes
The preview deployment does not run.

All the previous code such as loading indicators would be gone, the pages we had wouldn't load etc
A landing page component was created but then didn't use it and instead wrote directly inside the main file.

This can't be merged since it completely breaks what we had working before

2024-11-27 20:09 UTC, CodeYimin commented on view/src/pages/LandingPage.tsx
> +import React from "react";
There seems to be a landing page here, but also one in App.tsx

2024-11-27 20:09 UTC, CodeYimin commented on view/src/App.tsx
> -  const [page, setPage] = useState<"welcome" | "graph">("welcome");
The entire main functionality of the app has been deleted here and has not been rewritten

2024-11-27 20:09 UTC, CodeYimin commented on view/src/App.tsx
> +                    <>Welcome Page Content Here</> // Replace with your actual WelcomePage component
The actual WelcomePage component already existed in the previous code, there is no need to replace the actual code with a placeholder

2024-11-27 20:09 UTC, CodeYimin commented on view/src/App.tsx
> +                    <>Graph Page Content Here</> // Replace with your actual GraphPage component
^^ Same with graph page

2024-11-27 20:09 UTC, CodeYimin commented on view/src/App.tsx
> +            {/* Main Content Area */}
This seems to be a landing page, but there's another landing page in LandingPage.tsx

2024-11-27 20:09 UTC, CodeYimin commented on view/src/components/Navbar.tsx
> +    const [modalOpen, setModalOpen] = useState(false);
There should not be this many tabs, the previous tabbing was fine

2024-11-27 20:09 UTC, CodeYimin commented on view/src/components/Navbar.tsx
> +                <img
We should be using 2 space tabbing

2024-11-27 20:12 UTC, CodeYimin commented
I'd recommend putting the landing page inside LandingPage.tsx and keeping App.tsx mostly intact to avoid merge conflicts

2024-11-28 05:23 UTC, aainagargg commented
Addressed these issues by merging into Yimin's code.

2024-11-28 05:23 UTC, closed without merging